name: Release

on:
  workflow_call:

jobs:
  release:
    name: Run Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.10.0'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.3.0'

      - name: Install Dependencies
        run: bun install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bunx semantic-release
